### ISSUE TITLE
[JAVASCRIPT] Integrate "New Journal" Button to Allow New Journal Listing

### ISSUE THREAD

**Issue by camman00** [cse110-sp24-group3/cse110-sp24-group3#15]
As a user I want to be able to write my own title and create a new journal so that I can write different stuff

Spec:
- Clicking on the "New Journal" button should display new journals listed below

**Comment by Summerr12** [comment]
On Issue #16 I ended up creating a journal listing when you click on New Journal so I thought itd be of help here. I kept the code on the #16 branch because I didn't know if you already had a branch or not

window.onload = () => {
    createJournalEntries();
};

function createJournalEntries(){
    const journal = document.querySelector('.new-journal');
    journal.addEventListener('click', (event) => {
        const journalEntries = document.querySelector('.sidebar-module');
        const entryElement = document.createElement('div');
        entryElement.classList.add('journal-entry');
        entryElement.innerHTML = `
            <span>My Journal</span>
            <button class="edit-journal">
                <i class='fa fa-ellipsis-v'></i>
            </button>`;
        journalEntries.appendChild(entryElement);
    });
};
