### ISSUE TITLE
[FRONTEND] Sidebar Journal Listing HTML

### ISSUE THREAD

**Issue by camman00** [cse110-sp24-group3/cse110-sp24-group3#16]
As a user I want to be able to see all the journals that I created such that I can navigate to them with ease.

Spec:

- Journals are clearly listed on the left side bar.
- Styling inherits necessary global CSS variables.
- 3 '...' button on the side for quick actions (should display on hover)
- Component should be able to be updated dynamically.

**Comment by Summerr12** [comment]
Added a scroll feature to the sidebar for when too many journals spill onto the sidebar

**Comment by Summerr12** [comment]
Added a scroll feature to the sidebar for when too many journals spill onto the sidebar
