### ISSUE TITLE
[FRONTEND/BACKEND] Integate the localStorage to Populate Entries that Have Been Created

### ISSUE THREAD

**Issue by reisandylamdjani** [cse110-sp24-group3/cse110-sp24-group3#34]
As a user I want to be able to view my past journals so that I can refer back to it

Specs:
- The entries listed at the bottom of the "Add Entry" row should be associated to the current journals
- Data should be stored in localStorage, and be used to populate the entries at the bottom

**Comment by camman00** [comment]
As a group we decided to utilize a different data model which will reside in the form of an API that allows node to store the journals locally on the OS level.
