### ISSUE TITLE
[FRONTEND] Skeleton HTML for Entry Title

### ISSUE THREAD

**Issue by reisandylamdjani** [cse110-sp24-group3/cse110-sp24-group3#35]
As a user I want to be able to title my entry so that I know what I'm writing in my entry

Specs:
- Create a text field to allow user to write a title for their entry
- All styling should match the root element and MVP design
- If there is no any text, display "Untitled" with light grey color styling 
- If a user leaves the text input blank, it goes back to saying "Untitled"

![image](https://github.com/cse110-sp24-group3/cse110-sp24-group3/assets/101247244/8cf35602-01aa-4075-8ac3-928fdb399c4a)

**Comment by azpi-arte** [comment]
Talked with Reisandy and he approved my changes. Updated MVP to mimic this.
