### ISSUE TITLE
[BUG/QA] Journal Entry Text-Field is Resizable

### ISSUE THREAD

**Issue by camman00** [cse110-sp24-group3/cse110-sp24-group3#64]
![Image](https://github.com/cse110-sp24-group3/cse110-sp24-group3/assets/20690269/d706e0fa-6a2e-4c80-9644-85a006a62b4b)

The CSS needs to be updated so that the entry field is not resizable.

**Comment by reisandylamdjani** [comment]
This is just temporary until Logan finish his code mirror stuff

**Comment by camman00** [comment]
Perfect @reisandylamdjani!

@ILayon and @p3reddy when you have a chance when Logan is done would you please validate that this bug no longer exists and performs on different resolutions? Thanks!

**Comment by p3reddy** [comment]
<img width="1440" alt="Screenshot 2024-05-27 at 22 25 48 (2)" src="https://github.com/cse110-sp24-group3/cse110-sp24-group3/assets/142940827/407b7ced-27d9-454e-8725-75a6af5b2168">
CSS Fix looks good when tested with Firefox mobile viewer features.
