### ISSUE TITLE
[BUG] Sidebar Doesn't Fill On Scroll

### ISSUE THREAD

**Issue by camman00** [cse110-sp24-group3/cse110-sp24-group3#65]
![Image](https://github.com/cse110-sp24-group3/cse110-sp24-group3/assets/20690269/36978347-60bb-4e9d-bac4-2059edce7d25)

Fill error. The sidebar should fill in the white space here. Implications: compact UI.

**Comment by reisandylamdjani** [comment]
It seems to be fixed in one of the PR's
