### ISSUE TITLE
[FRONTEND] Add "Dev Mode" for Markdown Toggle Button

### ISSUE THREAD

**Issue by camman00** [cse110-sp24-group3/cse110-sp24-group3#7]
As a user I want to be able to toggle markdown mode for the document so I can experience markdown mode and formatted mode.

Spec:

- Button should follow the predefined style and typography from the root level
- Button should implement an accessible toggle feature (like an on/off switch) using minimal CSS and no JS.
- Button should integrate with backend functions

![image](https://github.com/cse110-sp24-group3/cse110-sp24-group3/assets/101247244/01da7861-d1d8-4e1a-bb63-79ec0e70982d)

**Comment by reisandylamdjani** [comment]
closing this issue since there is another issue that will integrate this changes
